//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasContainer : DbContext
    {
        public DatabasContainer()
            : base("name=DatabasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Användare> AnvändareSet { get; set; }
        public virtual DbSet<Bild> BildSet { get; set; }
        public virtual DbSet<Vänner> VännerSet { get; set; }
        public virtual DbSet<Profil> ProfilSet { get; set; }
        public virtual DbSet<Inloggning> InloggningSet { get; set; }
    }
}
