//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public int Id { get; set; }
        public string Intressen { get; set; }
        public string Söker { get; set; }
        public string Sökbar { get; set; }
        public int AnvändarID { get; set; }
        public Nullable<int> BildID { get; set; }
    
        public virtual Användare Användare { get; set; }
        public virtual Bild Bild { get; set; }
    }
}
