//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnvändareSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnvändareSet()
        {
            this.InloggningSet = new HashSet<InloggningSet>();
            this.ProfilSet = new HashSet<ProfilSet>();
        }
    
        public int AnvändarID { get; set; }
        public string Förnamn { get; set; }
        public string Efternamn { get; set; }
        public string Stad { get; set; }
        public Nullable<int> BildID { get; set; }
        public string PersNR { get; set; }
        public Nullable<int> Vänner_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InloggningSet> InloggningSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilSet> ProfilSet { get; set; }
        public virtual VännerSet VännerSet { get; set; }
    }
}
