//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InloggningSet
    {
        public int LoginID { get; set; }
        public string AnvändareEmail { get; set; }
        public string Lösenord { get; set; }
        public int AnvändarID { get; set; }
    
        public virtual AnvändareSet AnvändareSet { get; set; }
    }
}
